### ISSUE TITLE
QEMU Monitor Access

### ISSUE THREAD

**Issue by a-abraham** [amluto/virtme#20]
Is there any sort of shortcut that can be used to access the QEMU Monitor through virtme? 
Not sure if that's a valid use case or not. If not, is there any other way apart from using the QEMU monitor to Hot unplug a device? 

Referring to - https://en.wikibooks.org/wiki/QEMU/Monitor

**Comment by amluto** [comment]
ctrl-a c will give you the QEMU monitor.  ctrl-a c again will go back to the console.
