### ISSUE TITLE
feature request: support $KBUILD_OUTPUT for virtme-configkernel

### ISSUE THREAD

**Issue by domenpk** [amluto/virtme#24]
It would be nice if `virtme-configkernel` would not require source and output folders to be the same.

Supporting environment variable `KBUILD_OUTPUT` (already works for kernel build system) or an extra flag would probably be the way.

**Comment by marcosps** [comment]
@domenpk can you please test this PR?

**Comment by domenpk** [comment]
Thank you @marcosps. That works well for me.
