### ISSUE TITLE
Create a new release/tag for 0.0.4

### ISSUE THREAD

**Issue by marcosps** [amluto/virtme#49]
It would help packagers to have a new release, after 5 years of the 0.0.1 tag.

**Comment by amluto** [comment]
I tagged v0.1 and then I saw the new PR.  I'll tag v0.1.1.

There will be a short delay while the k.org people fix my kup account.  Unfortunately, I don't think I can make the github and k.org tarballs identical without some annoyance.

**Comment by marcosps** [comment]
@amluto no problem! I can pick from here of from k.org, I don't mind getting the package from github. Closing the issue since a new version was released.

**Comment by amluto** [comment]
I would be more comfortable if all the packagers use the *same* tarball.  I'll have the new v.0.1.1 tarball up soon, hopfully.

**Comment by amluto** [comment]
The final 0.1.1 tarballs are now on kernel.org in the spot mentioned in README.md

**Comment by marcosps** [comment]
@amluto thanks!
