### ISSUE TITLE
Mount disk

### ISSUE THREAD

**Issue by KamasuOri** [amluto/virtme#56]
May be a stupid question but  i meet fail while trying to mount .iso file. Could you tell what is going wrong please ?
-------------------------------------------------------------------------------------------------------------
sudo virtme-run \
--rw --pwd \
--kimg /home/uss/linux/arch/x86/boot/bzImage \
--memory 512M
-------------------------------------------------------------------------------------------------------------
root@(none):/home/uss# mount -t iso9660 test.iso /media/ISO
mount: /media/ISO: mount failed: Operation not permitted.
root@(none):/home/uss# whoami

**Comment by amluto** [comment]
IIRC there was a bug in some rather old QEMU version that caused this.  What guest kernel are you running and what QEMU?

In any case, this sounds like a bug that I may not be able to fix in virtme.

**Comment by amluto** [comment]
Closing because I don't have enough info to tell if this is a virtme bug.
